### ISSUE TITLE
Make state machine to work in a local context

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zcash-swift-wallet-sdk#1143]
The State Machine's actions use getLastScannedHeight many times. This should be considered global access to the value but State Machine is about to be changed to sync many ranges, ordered in a list. Every range should be considered a separate run so `getLastScannedHeight` or last scanned height must be provided within the context of the range run operates in. This will let the run to be fully encapsulated and independent on a global world. Even allowing to process ranges in a random order, not linear, not ascending or descending. Global LastScannedHeight will no longer be the core value that controls the whole sync.

**Comment by nuttycom** [comment]
This is no longer relevant.

**Comment by true-jared** [comment]
Closing as irrelevant.
