### ISSUE TITLE
Allow runtime switch of lightwalletd servers

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zcash-swift-wallet-sdk#1153]
Initialization of the SDK is done when an instance of `Initializer` is provided into the init method of the SDKSynchronizer. 

`Initializer` is basically a way how users of the SDK provides app/custom data to the SDK. URLs where the databases are stored as well as an endpoint. The SDK when properly initilalized uses this endpoint during the whole lifetime. That means any user of the SDK can actually initialize it with a different endpoint. X builds of the wallets can be done and every one can use a different endpoint. Let's call it a non-runtime setup. The endpoint is decided before the SDK is prepared and initialized.

The situation is much different when the SDK is initialized and someone would like to switch the endpoint runtime. There's no API at the moment that could offer such feature. It should be possible but it's a complex task that needs to be properly thought through. I see at least these to happen:

- update of the LightWalletGRPCService, new one must be be initialized and registered as a dependency => overriding the previous one
- broadcast somehow that this dependency changed, many parties rely on it and got the reference to the previous LightWalletGRPCService, all parties must throw it away and receive new one
- watch sync is (not) in process, stops the sync, clear out the states, etc.

To test it with valid alternatives, use (mainnet only!)

| Location | Host | Port |
| --- | --- | --- |
| North America  | [na.lightwalletd.com](http://na.lightwalletd.com/) | 443 |
| South America | [sa.lightwalletd.com](http://sa.lightwalletd.com/) | 443 |
| Europe & Africa | [eu.lightwalletd.com](http://eu.lightwalletd.com/) | 443 |
| Asia & Oceania | [ai.lightwalletd.com](http://ai.lightwalletd.com/) | 443 |

**Comment by tw0po1nt** [comment]
@LukasKorba Wondering if we can bump this. This would be very helpful to have.
