### ISSUE TITLE
Troubleshooting synchronization

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zcash-swift-wallet-sdk#1346]
### The problem
We believe the performance of synchronization in the iOS SDK is way slower than expected. Even though the conditions weren't made 100% precise, the sync on iOS vs. Android simulator/emulator showcased 14:40mins vs. 10mins sync time. All clues lead to the fact that something is dragging the time down.

### The goal
Research and review the synchronization and measure in depth and try to navigate to the parts of the synchronization that could be optimised. The goal is to make a conclusion something can be improved and the overall sync time lowered down significantly.

**Comment by LukasKorba** [comment]
I did measurements of the restore of the mainnet wallet, the same I use every time. The focus at the beginning was put on downloading of the blocks, we though that would be the place where to start digging and potentially discovering issues. Surprisingly, the measured times uncovered a different problem.

overall time: 881s (~14:40min)
scan: 738s
download: 63s
clear scanned blocks: 72s

The CompactBlockProcessor is a state machine so every action is measured in an isolation. If we see 738s being spent in the scanAction, that's what really happened. It doesn't say anything about the rust layer or a use of rust method but the state machine simply spent time with this action before passed the context to the next action.

We clearly see that scan action takes ~84% of all sync time and that is way more than anyone would expect. On the other hand, 63s for the download is way better than expected and proof that parallelization of downloads work. The next 100 blocks are almost always prepared and the download action simply passes the context almost immediately after being called.

The next step is to figure out what takes time in the scan action.

**Comment by LukasKorba** [comment]
After another batch of testing and measurements with the focus on scan action we now know what is the root cause of the slower performance.

The progress reporting is the root cause. The rust methods are super fast, by magnitude faster than the code that is supposed to gather the data and report the scan progress to the observers.

I made several changes in the code to get times for comparison.

#### No progress reporting at all:
overall time: 385s (~6:25min)

#### No progress reporting but computing and receiving the scan progress from rust:
overall time: 534s (~8:54min)

#### Progress reporting throttled to broadcast data only every 5th cycle:
overall time: 601s (~10:01min)

#### Full code before any change:
overall time: 881s (~14:41min)

We finally understand what's wrong and how big the room for improvement potentially is. The next step is to review the complexity of progress reporting. There are several layers, all in a concurrent environment. 

#### The goal is to get as close to the best possible time which has been measured as `no progress reporting at all`, taking 385s vs. 881s. 

That is a potential of x2.3 improvement!

**Comment by LukasKorba** [comment]
I also noticed this:
At the beginning, the `zcashlc_get_scan_progress` takes around

0.03039097785949707s

but it only gets worse with every call…

a minute later
0.08229303359985352

another minute later
0.096343994140625

towards the end of sync
0.1504840850830078 that is x5 compared to the beginning

**Comment by str4d** [comment]
The slow `zcashlc_get_scan_progress` will likely be fixed by the change I made in https://github.com/zcash/librustzcash/pull/1122.

**Comment by LukasKorba** [comment]
I did detailed analysis of the ScanAction with the focus on the progress reporting. It's all collected in the following image:

<img width="1114" alt="Screenshot 2024-01-23 at 17 31 41" src="https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/assets/7198042/c598b76f-e9eb-4878-8256-dbe558bda8b1">

At the root of the action there are 2 independent parts. 
1. the actual scan on the rust side
2. the progress reporting that includes gathering of the data from the rust

Getting the scan progress is slow but it's something that hopefully is fixed as mentioned [here](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/issues/1346#issuecomment-1905873431)

What follows is the attempt to let all subscribers know the progress update. Progress % value is just a part of the struct that is being broadcasted. Other values in the struct are
```swift
init(
        syncSessionID: UUID,
        shieldedBalance: WalletBalance,
        transparentBalance: WalletBalance,
        internalSyncStatus: InternalSyncStatus,
        latestBlockHeight: BlockHeight
    )
```

and those balances represent another 3 independent rust calls. In the end, creation of such struct takes 352s out of 597s for the reporting. The rest is the getScan.

### Suggestions
What I think is worth investigating is to figure out how to reduce the frequency of the reporting. We basically face 

1. If there is no reporting at all, we could reduce the sync time by 597s, that is almost 10 minutes so sync would last ~6min instead of 16. It's a hypothetical situation because some reporting is still needed. On the other hand this gives us an overview os what could be possible and how big the room for the improvement is.
2. The worst case is to report as frequently as possible (current state). The current rate is every 100 blocks, matches the batch of the scanned blocks. That also means we try to update the values every 100 blocks, including getting the balances even though those may or may not changed from the last call. This is super inefficient approach. 
3. One possible and easy optimization is to throttle the reporting. This could by done by time or instances. We could report every 5th cycle, that would mean report after every 500 blocks are scanned instead of 100. Or by time, every time at least 2 seconds passed from the last reporting, etc.
4. The best would be to maybe combine throttling + some logic that determines if there's even anything to report. If the balances stay the same for the next 4 minutes, there's no point in trying to frequently ask rust about the balances. The scan progress (%) is probably something that updates frequently by throttling would work, slightly worsening the UX fro the clients. When I tried that every 5th report, the % was jumping up in a bigger chunks and that started to feel a bit like a faked or unnatural.

**Comment by pacu** [comment]
I've been syncing my old wallet for the last few days with many interruptions in between. The whole system becomes quite clunky but the bursts of hard processing don't seem to be constant, so the system is being slowed down overall, also the UI becomes irresponsive at times when trying to spend before syncing, so there's probably something blocking the main thread as well that could be investigated.

One issue is that when going through the sandblasted part of the blockchain the scanned ranges take longer, so deciding in terms of block ranges is not a good metric because it depends of how heavy loaded a batch is. 

Probably as @LukasKorba is some throttling should be done all across the stack so values are only reported on value changes, although that's easier to say it than to actually code it. The App is not stressing the memory but there are quite big I/O values reported by Xcode's debug pane.
