### ISSUE TITLE
The Info.plist file is missing the required key: CFBundleShortVersionString

### ISSUE THREAD

**Issue by gades** [Electric-Coin-Company/zcash-swift-wallet-sdk#1437]
#### If so, please list the steps to reproduce below:
1.  Add Zcash Framework 
2.  Archive
3.  Push App to TestFlight 

### Expected behaviour
App should be accepted by Apple

### Actual behaviour + errors
The bundle 'Payload/{my_app_name.app}/Frameworks/libzcashlc.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: df14a2d9-2172-4dfb-ab06-cef26b9c91a5)

- App Version:

`                        repositoryURL = "https://github.com/zcash/ZcashLightClientKit";
                        requirement = {
                                kind = exactVersion;
                               version = 2.1.8;
                        };`

**Comment by LukasKorba** [comment]
Fixed in SDK [2.1.10](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/releases/tag/2.1.10)
