### ISSUE TITLE
[Research] reproduce duplicate-nullifier bug and spice with a reorg

### ISSUE THREAD

**Issue by pacu** [Electric-Coin-Company/zcash-swift-wallet-sdk#297]
This was a research experiment originated by the duplicate nullifier issue back in 0.9.2 

Branch: experiment/bad-anchor-research

The test reproduces the duplicate-nullifier error and also adds a reorg in the middle. 

branch: experiment/bad-anchor-research

Original Draft PR: https://github.com/zcash/ZcashLightClientKit/pull/272/commits/351e5ce01075c873e527cc177d0b2e8655a93826

**Comment by nuttycom** [comment]
Closing as obsolete.
